version: '3'

services:
  v1:
   
    build:
      context: .
      dockerfile: ./Dockerfile
    image: "node-mysql"
    container_name : "node-mysql"
    depends_on:
        - mysqldb
    stdin_open: true
    volumes : 
        - ./:/app
    tty: true
    ports:
      - "3000:3000"
  mysqldb:
    container_name: mysqldb
    restart: always
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=demo
      - MYSQL_ROOT_PASSWORD=FETCH_PASSWD_FROM_ENV
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
    ports:
      - 3306:3306  
volumes: 
   db-config:
   db-data: